version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose images
# docker-compose logs --tail 20 repo_name

services:

  postgres_db:
    image: postgresforbot:latest
    ports:    # Set up ports exposed for other containers to connect to
      - 5432
    networks:
      - app-tier
    volumes:
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  darkside:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    ports:
      - 9002:9002
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge
